apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ihouse-cd
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/sagnofelix/ihouse-cd.git
    targetRevision: HEAD
    path: ./
  destination: 
    server: https://kubernetes.default.svc
    namespace: ihouse-cd

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true