apiVersion: apps/v1
kind: Deployment
metadata:
  name: ihouse-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ihouse
  template:
    metadata:
      labels:
        app: ihouse
    spec:
      containers:
      - name: ihouse
        image: jeanfelixsagno/ihouse:0.0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: ihouse-service
spec:
  type: LoadBalancer
  selector:
    app: ihouse
  ports:
  - port: 3000
    targetPort: 3000
